name: fluffboost
services:
  postgres:
    image: 'postgres:17-alpine'
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'fluffboost-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
        - '-d'
        - postgres
      interval: 5s
      timeout: 20s
      retries: 10
  redis:
    image: 'redis:8-alpine'
    ports:
      - '127.0.0.1:6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 20s
      retries: 10
  bot:
    build:
      context: .
      dockerfile: apps/discord/Dockerfile
    init: true
    env_file:
      - apps/discord/.env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  fluffboost-postgres-data: